# Generated by Django 5.2.5 on 2026-03-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Ключове слово')),
                ('app_name', models.CharField(max_length=100, verbose_name='Назва файлу (напр. notepad.exe)')),
                ('path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Шлях (заповниться само)')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Ключове слово')),
                ('response', models.TextField(verbose_name='Що відповісти')),
            ],
        ),
    ]
